### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by bezunakarmi** [younginnovations/opencontracting-moldova#19]
Export to CSV doesn’t work properly:

- It exports not results of searching but all? List of items
- The CSV file does not contain diacritics

**Comment by bezunakarmi** [comment]
Currently new csv are generated, when new data are fetched. The **export to csv** button is only used to download the whole data set results rather than search results.

The dataset is too large to download search results.

**Comment by anjesh** [comment]
@dc-coder diacritics doesn't render in Microsoft Excel but works well in linux - libreoffice and open office. 

As for the csv export, i am thinking of putting the export functionality alongside json download. We can define the structure of CSV content and if required there might be multiple CSVs as well and remove CSV download from the search results interface. What do you say? @dc-coder

**Comment by mireille-raad** [comment]
It would be more helpful if people downloaded the full data in csv format next to json, rather than just what they see on a grid (4-5 fields) - Once csv is downloaded, filtering can be done.

Can we include some default  readme.txt that points to the schema of the data or some help documentation online?

**Comment by anjesh** [comment]
That sounds good. In fact we are thinking the following

* remove the export csv from all the current search results pages
* replace "Download json" with "Download data"
* "Download data" page will contain the followings
  * "Download JSON"
  * "Download CSV" There could be multiple csv files. For example, one tenders csv file, one contracts csv files, one goods&services csv file with de-normalized contracts data
  * There would be readme txt with information for each file
  * There will be last updated datetime of the data
  * we could also provide the information on the API (just a thought for now)

@dc-coder, your thoughts? We need to define the content of each CSV file so that it contains the information people would be interested in and that they can use.

**Comment by mireille-raad** [comment]
sounds way better :) 

Let's publish in CSV all that is available based on how OCDS would recommend. If there are extra fields we can add them of course. How many fields are outside OCDS? 

Anyone downloading the data is fairly advanced, we can decide for the users what to see in the UI... but for advanced users, better share all publicly available data.

Do you feel comfortable with suggestion or do you rather i check with the team?

**Comment by anjesh** [comment]
Yes sounds good. This is what we are thinking http://moldova-demo.yipl.com.np/downloads and  the text needs to be updated there as well as the csv template. We still need to look into OCDS recommended CSV templates. 

But my quick opinion is to go beyond OCDS and follow the easy convention. For example http://standard.open-contracting.org/latest/en/implementation/serialization/#simplified-single-table shows an example of csv where if there are multiple items for a given tender then it just gets extended and there are few tenders in moldova with 100s of these items - making the csv useless to use manually. Instead we can have csv where the items are listed in single column with other tender metadata de-normalised. Similarly we can have separate templates for contracts as well. 

If people want OCDS compatible, they can always get hold of json data. 

In any case, lets keep this discussion open and would be ideal to get opinions with the team as well.

**Comment by anjesh** [comment]
Need to rename the csv column names as per OCDS. Also need to put the link to json and link to page in the csv as well.

**Comment by anjesh** [comment]
We just need the two CSV files with the following mentioned field-names. The other files could be easily derived from these two CSV files.

## tenders.csv

* ocid
* id
* title
* description
* status
* procurementMethod
* tenderPeriod/startDate
* tenderPeriod/endDate
* procuringEntity/name
* procuringEntity/id

## contracts.csv

* ocid
* id
* title
* description
* status
* period/startDate
* period/endDate
* value/amount
* value/currency
* dateSigned
* items/description
* items/id(CPV) 
* procuringEntity/name
* procuringEntity/id
* suppliers/name
* suppliers/id

**Comment by bezunakarmi** [comment]
Above mentioned change has been made to csv file. Please do have a look.
![screen shot 2017-05-12 at 5 28 17 pm](https://cloud.githubusercontent.com/assets/12218329/25996781/b2589138-3738-11e7-92bb-72a948513511.png)

![screen shot 2017-05-12 at 5 29 58 pm](https://cloud.githubusercontent.com/assets/12218329/25996785/b52eabc2-3738-11e7-8c06-c98cf6e675ed.png)
