### ISSUE TITLE
Search filter on contract page 

### ISSUE THREAD

**Issue by bezunakarmi** [younginnovations/opencontracting-moldova#8]
Search filter on contract page to include Contract authority, Economic operator, goods, services, CPV code

**Comment by bezunakarmi** [comment]
cc: @timilsinabishal

**Comment by anjesh** [comment]
@timilsinabishal @bezunakarmi please mention what confusion you have.

**Comment by bezunakarmi** [comment]
As we have known 
Contract authority-> Procuring Entity/Buyer,
Economic Operator -> Contractor/Supplier,

Do we need a free text search for buyer, supplier and goods & services or we could just add drop down where we can select related parameter for searching contracts?

**Comment by anjesh** [comment]
I am assuming the following. Advanced search filter list should appear in all the following pages where there's only free-text search field now. And have the following criteria for search. @dc-coder?

Search filter options
* Contract authority
* Economic Operator
* Goods & Services (CPV code) - Goods & service name and CPV code in bracket rather than separate dropdown.

http://moldova-demo.yipl.com.np/contracts
http://moldova-demo.yipl.com.np/procuring-agency
http://moldova-demo.yipl.com.np/tenders
http://moldova-demo.yipl.com.np/goods

**Comment by mireille-raad** [comment]
Do you think it would make more sense to have one advanced search (the one on homepage), re-use that component on all the pages you mentioned?

This means you might need to add some fields to the main homepage search like the cpv code. But instead of re-coding, you can re-use it everywhere. What do you think? possible?

If it is not possible to reuse homepage search, can we add to the search filter options:
- date range
- range (amount)

**Comment by mireille-raad** [comment]
One more thing, if you are implementing an advanced search, i know the ticket title says on contract page... but does it also make sense to copy it to  agency, goods and services/work and other pages ?

**Comment by anjesh** [comment]
We are rethinking the design as well, in a sense that currently all the different pages show information differently like 

* goods&services shows the list of goods, 
* agency page shows the list of agencies, 
* contractor page shows the list of contractors. 
* contract page shows list of contracts 
* tender page shows list of tenders

We are thinking on couple of options

* do we need to have all these different adv search criteria there or not in all these pages (apart from tenders and contracts list page)
* we replace the existing listing in these pages with the search box, which takes to the adv search page with options to further filter on the results
* rethink the existing list fields in goods, agencies, contractors list page and see if those could be replaced with some other list, or some meaning charts/graphs or have consistent list

@dc-coder Do you have any thoughts on resolving this confusion and creating the consistent list/pages/content?

**Comment by anjhero** [comment]
Hi all, 

We're thinking of putting a contract explorer section. This section will be a block that is sticky to the bottom of the browser. This section will be visible all the time in every page. The visibility will not be affected by a scrolling behavior. 
![contracts-explorer_btn](https://cloud.githubusercontent.com/assets/528549/26050037/ed5f9196-397c-11e7-9350-8437ca9ef4e3.png)

This "Contracts explorer" section will be a clickable block. Clicking on this section would bring out filter options for the contracts that we want to search. 
![contracts-explorer_btn_expanded](https://cloud.githubusercontent.com/assets/528549/26050047/f7eeb52e-397c-11e7-824a-0bbcce548031.png)

Here's an example of the prototype (It is an animated gif file. It might take some time to load):
![moldova_contract-explorer_prototype_2](https://cloud.githubusercontent.com/assets/528549/26050205/7f62eeee-397d-11e7-80df-1c44d3f46b9e.gif)

**Comment by bezunakarmi** [comment]
Contract explorer has been added to the portal. Please do explore and  feedback us about it.
![screen shot 2017-05-17 at 11 39 06 am](https://cloud.githubusercontent.com/assets/12218329/26140333/de757cac-3af5-11e7-812a-ee216ad31881.png)

**Comment by mireille-raad** [comment]
This looks excellent :) thanks for the great interface.

I know this feature has been done already... but I just thought that it would be really useful if we add the filter for the different stages of the procurement process (planning,tender, award, contract, implementation) - it might help people find the tenders, the contracts, the planned etc... 

If it is not much to do and if you feel like it, i think it would be neat to add...but given time constraints, I understand if you can't add it :)
